name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest tested rust version
        uses: dtolnay/rust-toolchain@1.93
        with:
          components: rustfmt, clippy
      - name: Run cargo check
        run: cargo check --benches --tests --examples --all-features
      - name: Run cargo clippy
        run: cargo clippy --benches --tests --examples --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used --no-deps
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run cargo doc
        run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: --cfg docsrs
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: npm install -g wasm-pack # Use precompiled binary
      - name: Run cargo build (debug)
        run: cargo build --all-targets
      - name: Run cargo build (release)
        run: cargo build --all-targets --release
      - name: Build for WASM (debug)
        run: ./build.sh debug
      - name: Build for WASM (release)
        run: ./build.sh release
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo test
        run: cargo test --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@1.89
        with:
          components: rustfmt, clippy
      - name: Check MSRV compatibility
        run: cargo check --all-features
